databases:
  - name: payroll_db
    databaseName: payroll
    user: payroll_user

services:
  - type: web
    name: payrollpro
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: payroll_db
          property: connectionString
      - key: SESSION_SECRET
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.0